### ISSUE TITLE
Twitter Bot (3/5) - Twitter Bot Front End

### ISSUE THREAD

**Issue by masonicGIT** [21hackers/git-money#124]
**Current Bounty: 23,918 bits / ~ $10** [Proof](https://live.blockcypher.com/btc/address/3LGTSHL2aqCJMDTC1P3CpbmbdER4QEWbbA)
*Submit a pull request containing your bitcoin address that resolves this issue and automatically get paid the amount above if it's merged.*

**Bounty Details:**
Create the Twitter Bot front end to publish tweets. Should take in a string and publish to Twitter

**Comment by hems** [comment]
Should be very easy to accomplish using a package like https://www.npmjs.com/package/twitter .

see #125 anyway!

**Comment by masonicGIT** [comment]
Closing - This feature has already been incorporated.

3H1YSG26mhENqQMG8hSrTNbaBnopWNNiNP
