### ISSUE TITLE
21 Marketplace Endpoint

### ISSUE THREAD

**Issue by masonicGIT** [21hackers/git-money#127]
**Current Bounty: 23,919 bits / ~ $10** [Proof](https://live.blockcypher.com/btc/address/3CPSwLHj8qL1QabAEFuVpTuuMz8Sb8oWQs)
*Submit a pull request containing your bitcoin address that resolves this issue and automatically get paid the amount above if it's merged.*

**Bounty Details:**
Create a marketplace endpoint that can store new issues and update bounty information (balance) using webhooks

**Comment by wbinns** [comment]
Closing.
