### ISSUE TITLE
Add retina-friendly graphics

### ISSUE THREAD

**Issue by bitcoin-legion** [21hackers/git-money#129]
**Current Bounty: 23,949 bits / ~ $10** [Proof](https://live.blockcypher.com/btc/address/3Pko5UtJ4NJwZ5pJutFJypJMqnPQKiSGk4)
*Submit a pull request containing your bitcoin address that resolves this issue and automatically get paid the amount above if it's merged.*

**Bounty Details:**
Make graphics retina friendly (sitewide)

**Comment by rashagen** [comment]
Any particular backwards compatibility requirements on this?

**Comment by wbinns** [comment]
@rashagen Hi there! They should just display natively if the device isn't retina-capable. Also, apologies if I am not understanding your question.

**Comment by CumpsD** [comment]
You guys mean just these images?

![image](https://cloud.githubusercontent.com/assets/1201644/14067609/3712fc70-f468-11e5-9a28-4952ab13ce77.png)

Am I missing something?

**Comment by wbinns** [comment]
Closing for now.
