### ISSUE TITLE
Improve Test Coverage

### ISSUE THREAD

**Issue by bitcoin-legion** [21hackers/git-money#150]
**Current Bounty: 23,961 bits / ~ $10** [Proof](https://live.blockcypher.com/btc/address/3HKQdSVHDQkunyjK7frhWDV6kU2Nmxwfx1)
*Submit a pull request containing your bitcoin address that resolves this issue and automatically get paid the amount above if it's merged.*

**Bounty Details:**
Setup and write a few tests in the git money app to help improve test coverage

**Comment by ronotono** [comment]
@wbinns can I add node.js to the project and add tests rather than using python?

**Comment by masonicGIT** [comment]
@ronotono Hello, would be great to stick with python :-)

**Comment by wbinns** [comment]
Closing.
