### ISSUE TITLE
git Money

### ISSUE THREAD

**Issue by wbinns** [21hackers/git-money#21]
###### Reward (13aWiexHS6mv8oqRy2wBb6uFsr2W3hzpKe)

The Times 03/Jan/2009 Chancellor on brink of second bailout for banks

**Comment by wbinns** [comment]
cc: @arik-so @desantis

**Comment by masonicGIT** [comment]
http://localhost:21337/badge/1JLRXD8rjRgQtTS9MvfQALfHgGWau9L9ky

**Comment by aiouy** [comment]
![alt-text](https://git-money-badge.mybluemix.net/badge/13aWiexHS6mv8oqRy2wBb6uFsr2W3hzpKe)
