### ISSUE TITLE
Set up display of home page by visitor language

### ISSUE THREAD

**Issue by bitcoin-legion** [21hackers/git-money#215]
**Current Bounty: 2,874,596 satoshis / ~$12** [Proof](https://live.blockcypher.com/btc/address/345v1FeutR2wWoAZEXtxNzJWy9RhVacXkb)
*Submit a pull request containing your bitcoin address that resolves this issue and automatically get paid the amount above if it's merged.*

**Bounty Details:**
There are several files in the translations/ folder, representing versions of the home page in a specific user language. Refactor index.html so that it displays the in the native language of the visitor by default.

**Comment by cryptocharles** [comment]
i can work on it, but we need more than a static site. Something like [jekyll](https://jekyllrb.com/).

**Comment by masonicGIT** [comment]
@cryptocharles Would you mind elaborating on the need? We're ok with this, would be happy to discuss further to figure out what the specs should be. Please find us on https://slack.21.co to discuss further. My username is @mason

**Comment by Cerx-pw** [comment]
Is this still open? A simple javascript could do that.

**Comment by matthewjamesr** [comment]
@Cerx-pw another user and I have both submitted PR's. Would love for you to take a look at each implementation. I went with a more basic approach and refactored it into `public/js/custom.js`. Reference #221.

**Comment by gratiscoin** [comment]
http://stackoverflow.com/questions/17803702/auto-detect-language-and-redirect-user good code here that might help

**Comment by wbinns** [comment]
Closing.
