### ISSUE TITLE
Twitter Bot - @gitmoneyco

### ISSUE THREAD

**Issue by chuck-nasty** [21hackers/git-money#23]
# Twitter Bot 

When bounty is launched and/or the bounty is raised -- > hits webhook --> tweet sent @gitmoneyco

**Comment by chuck-nasty** [comment]
reminder: add bounty img to origination tweet

**Comment by wbinns** [comment]
Closing this for the time being until we start pushing into social media. We were thinking we could do a pilot first to gain user feedback to then figure out the best way to enhance the product (and in turn amplify via social media).
