### ISSUE TITLE
Slackbot - 21co.slack.com

### ISSUE THREAD

**Issue by JayCoDon** [21hackers/git-money#24]
## Slackbot

In connection with #23, implement a slackbot to alert users of a specific slack group (could be 21co) that a new bounty has been implemented:

Bounty is posted --> slackbot posts to the channel with the URL to the issue

If Git Money ever created its own slack group, the same thing could be implemented there.

**Comment by masonicGIT** [comment]
nice!

**Comment by wbinns** [comment]
Let's look at this after we do the pilot program.
