### ISSUE TITLE
Bounty Browser

### ISSUE THREAD

**Issue by davemc84** [21hackers/git-money#25]
I know that the description mentions that issues would be posted through various social media channels, but would it be helpful to have some kind of tool that allows developers to search all open issues for which there is a bounty?  This will obviously be dictated by the information required when the bounty is submitted, but the basic information returned would probably be something like the following:
* Bounty amount
* Issue description
* Programming language
* Deadline?

In addition, there can perhaps be some kind of view that shows issues with the highest bounty, closest deadline, etc.

My thinking is that this could streamline things from the perspective of the developers and perhaps create more of an efficient market.

**Comment by wbinns** [comment]
Hey @davemc84 - cool idea, @masonicGIT and I were talking about this. Perhaps we could put it in JSON and allow a URL to be curled that provides this info. We could also show it on the Git Money website. I will subdivide this into smaller issues so maybe other people can pick up and help contribute fragments (or to make it more manageable) to help piece it together.
