### ISSUE TITLE
create 21.co Flask endpoint for bitcoin-charging python script 

### ISSUE THREAD

**Issue by fredzannarbor** [21hackers/git-money#250]
I have a  python script that I would like to make available via a 21.co command line end point along these lines

https://21.co/learn/monetize-the-command-line-with-bitcoin/#next-steps

I have a 21.co bitcoin computer.  I think you need to have a 21.co computer too.  My goal is to have this script available in the 21.co marketplace.

https://21.co/mkt/

The script is Python 2.7, takes a couple of parameters and a text file, and returns a shorter text file.   

From what I've read on 21co the best way to accomplish this is using Flask.  

I am super busy and would like to delegate this task.

**Comment by wbinns** [comment]
@fredzannarbor Thanks for the interest. We may set up some additional tasks in the future. We'll ping everyone once they are available. If you'd like to set up a bounty for something like this, that would be great. We'll close this for now and reach out to you, then.
