### ISSUE TITLE
When clicking on Browse current bitcoin-payable Issues on GitHub. its only search label for 21hackers

### ISSUE THREAD

**Issue by juliencousineau** [21hackers/git-money#253]
Hi, 

I love your concept, its awesome. Actually I was thinking doing something like that, when I stumbled into your repo.

But,
When clicking on Browse current bitcoin-payable Issues on GitHub. its only search the label "git-money" for 21hackers

It will be better if it goes there : https://github.com/search?utf8=%E2%9C%93&q=label%3A%22git+money%22+

Thanks J !

**Comment by wbinns** [comment]
Thanks for mentioning this. We're going to change the way we handle listing issues, as well as the way people discover them, that way it will be even easier than having to browse the label.
