### ISSUE TITLE
Set up social media accounts for Git Money

### ISSUE THREAD

**Issue by wbinns** [21hackers/git-money#35]
- [x] Twitter
- [ ] Facebook
- [ ] Google Plus

**Comment by blakemiles** [comment]
on it

**Comment by chuck-nasty** [comment]
also - add urls to the landing page when these are all done!!

**Comment by wbinns** [comment]
Let's put social media on hold until we have more live gigs in the app, then once they are consistently present, let's start posting them to social media! Let me know if you guys disagree, otherwise, will reopen.
