### ISSUE TITLE
Refund Backers on Closure

### ISSUE THREAD

**Issue by maurbeck** [21hackers/git-money#6]
If issues are closed (rather than accepted) the backers are refunded.

**Comment by wbinns** [comment]
@masonicGIT Let's turn this into a bounty.

**Comment by wbinns** [comment]
@masonicGIT Actually, I just realized this wouldn't apply to the pilot since we are going to single-back stuff. We'll need to implement this in versions after that (thanks @maurbeck). Let's close for now.
