### ISSUE TITLE
Time boxed bounties

### ISSUE THREAD

**Issue by maurbeck** [21hackers/git-money#7]
Time boxes for bounties are necessary to keep money from sitting in limbo without recourse for backers. For x days from original bounty post, subsequent backers vote on the duration of the issue (z days). Votes are weighted according to contributions.

**Comment by wbinns** [comment]
Let's leave bounties open for the moment, we were thinking we'd start with very small denominations and focus on very objective projects that aren't funded by multiple people (just single backers, the repo owners).
