### ISSUE TITLE
Testing: 2016-02-21 20:37:04.069981

### ISSUE THREAD

**Issue by davemc84** [21hackers/git-money#70]
<h6>Reward  (1DxmRibidDa1B9VGLmTa55vvqzd4YTtNUc)</h>

![BOUNTY](http://git-money-badge.mybluemix.net/badge/1DxmRibidDa1B9VGLmTa55vvqzd4YTtNUc)

**Comment by wbinns** [comment]
Closing this to clean up Issues - please feel free to reopen if you need it for continued testing.
